language: r
cache: packages
env:
  global:
  - secure: "Kx590U+7waGrLy8p+mso16zo2oGRn+s9EHZDtX/U8QBoDBLv7oEvkOYVlsJKZ22eiXF88NIqHPpmq3tOEm5edzgnTJFpeqkxwbFI66+tEcdFrnWpLK/9j7g42HR76v5eqcLpRWNTNH4ND0yZlDzwObXFLp4n2v9D6SnbuX/FXjiGBcsq97i4ev4rCfKwLQbwl7uXQTBmEwoqC9kYils/C4GujDXxek1i4oMkb8PEBlZHyC00G7qBSB1+nAkwHhar2Uw8QUYIUhL4yXmFw9cjtrzDD/TdN1cE77EJSw+9KxnQYs2cw21hkw6PsxOT0apj/+EL9aj7uU/uFZX2OrG5hoydwhJquFDZE5uWSZXBJtWpQx2fNMXa3rfWluut5gATCDcIobt1aDlHY2UQaA7WTexfJaX+t/ZMRy9VJKw9WuJs1ncElI5vT05onJD62RQxwHe7E8gxNkcZPlX8q+s9TIs3IaiZ7Gg8bpnxgiKPRePF8Ifsnncvg7DzQdLiph6nCoCMALY75pH8ihGxBQCDoQxKLEHSwc9GRn/NwtLWUMxsgZgeZYC/jsEGvHUjYgYQe/4YpptrgWuqLpCeiomDwgwKeU/DoAzp8akHG6alapW4SkOGwwTkzSlZV9h2pOdrxafi9WJlXsnZ/6SaS7kkhb6R1KctpDsDhMaYEwRnJJc="
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh
sudo: required

r_binary_packages:
  - ggplot2
  - data.table
  - haven
  - openxlsx
  - readxl
  - dplyr
  - tikzDevice

r_packages:
  - rio
