language: r
cache: packages
env:
  global:
  - secure: PXSNgd3uFca/LIhW86thBEnoH4SvU2t/LCCpkX0VO4ulooJI7HgZHGmkaorOv229FmMzN2HRAEeIPBS9qzpJxcRzua8Kp9GhumVzs9fQ9apJVVsyhrZcv4x7jgq85/aIZ/1pJeeQQ0PairJhvQ7gppYZx0tzXkEbGu1jUJ9ftf4XArh1Z+LOTB2qHXrBs3cj70+3SVzqw9/e7CUbL4HvqLZDBzpShYVEdGjikyyoE34+jrR4MYIqYMQ0njMWUuq3zhqp/WcfT2ESgi1Ptm1PebNpKWMUyqjK5tNpUENGT7BzziTJjFJJYirUZNRXrJBwLw4qAslSfsRJkcBLN8WST4govTVbdiaFV25yLrSgm87+ZyKpcANrmrNfshhaZ2HBDZQQttlCNoIwmeT8XkIH7eGhTYC0PI9iuptpF8ATFN++RTitXNFWOKiaZerQ8/8zn4/GRdmwOwK2a1Krp+eTfEOOTNj1dTfFe1j0IGABaMPIiPJ/UO1wrQzzkAQMJrUafW8/z/UTizKKS3gDs+uiPuDlnXU8DsgV3QzI+l2Vi4wO+snSJdfeAn7MZ8mL/9/dLhbe1B62sj2b/+tsjTUb/e8o8P7i4tssoVUPjyOye5VPl9gEaMhURnrAoPv1nO8v8co5DYoIghp3mEWdlNMIHEye+VUBhIbsxBstyxW1hO8=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- ./_build.sh
- ./_deploy.sh

r_binary_packages:
  - ggplot2
  - data.table
  - haven
  - openxlsx
  - readxl
  - dplyr
  - rio
