language: r
cache: packages
env:
  global:
  - secure: "KtxjzxpLPK5YgUExbp+++/Esr0yJ9ScEeHCKUkBu+QEKBZxoa4lNOrXXjWVHlrQmZwwhdwV282PiaabMgTLtm3RXBi0eL83HoGiY3axhWaRHPLmoSYaNzlMZl24X6z5QmKrT9/3ounZGuzG586vnAAsknOscVc9DTLYPAnm6vgC7C9M+h8mbEoUzwdUV78X8qET2+Cmh/+njqUY9LrYgkCmyTcHOTKgg3WOOpBhFb+zDWUrOp9IMHO1IRTFl84CVovoJpMmQRtJtoxBzwfuYTA+NFlmZTZDJJsldVq23HuFQCXQuqhFtADc+DyKeqZCWFlGgBi7kNZ6bIP/3PJRT/sc2Dnf2kqYc9P0ninEwewJQnzwWt9WXJDCU2qvqtobWIgpmkOej10Wdr4qRNdtbF87RC6AKE4uuUatwX5yTEruzmqrh9oHUfxzk0OQMvZ2WAuA+ptC/r8BRjFxJmAA0RYzq24ZQUa7FTF+Lieu2M5oY19ajZRMx4XHVvBLcJ1Ufk3aKLcSTSnEC/utdv1aaldpEvyIHLIalji+ZsLCLXuh5nWlkahXz+b+JDQTNF1E8ECPmMBgVdd8d+HLt7hVQc6Bz2qjmIcMAebDYmku8ilezwFB9enHjiyR+8iWstlQEGEQd4P4hyjZwjA3LJueohFZTtII0aapjrLbpDzsJ43E="
before_script:
- chmod +x ./_deploy.sh
script:
- make html
- cp -fvr prebuilt_book/* _book/
- ./_deploy.sh
sudo: required

r_binary_packages:
  - ggplot2
  - data.table
  - haven
  - openxlsx
  - readxl
  - dplyr
  - tikzDevice
  - sandwich
  - lmtest
  - broom
  - data.table
  - reshape2
  - tidyr

r_packages:
  - devtools
  - rio

r_github_packages:
  - gforge/Greg
